const express = require('express')
const exhbs = require('express-handlebars')
const mongoose = require('mongoose')
const dotenv = require('dotenv').config()
const routes = require('./routes')
mongoose.connect(process.env.MONGODB_URI)
const db = mongoose.connection
db.on('error', () => console.log('mongoose error'))
db.once('open', () => console.log('mongoose connected'))
const app = express()
const port = 3000
app.engine('handlebars', exhbs({ defaultLayout: 'main'}))
app.set('view engine', 'handlebars')
app.use(express.urlencoded({ extended: true }))
app.use(express.static('public'))
app.use(routes)
app.listen(port, () => console.log(`It is listening on http://localhost:${port}`))